### ISSUE TITLE
Testing Checklist

### ISSUE THREAD

**Issue by philipwalton** [philipwalton/ingen#3]
## Modules
- [x] config
- [x] file
- [x] page
- [x] permalink
- [x] post
- [x] query
- [ ] site
- [x] taxonomy
- [ ] template-data
## Generation
- [ ] Draft posts are excluded by default (including their taxonomies).
- [ ] Post pages are created if they specify a layout.
- [ ] Post pages are not created when no layout is specified.
- [ ] Taxonomy pages are automatically created when a corresponding layout file is present.
- [ ] Additional pages are generated for pages with query and `query.limit` parameters (pagination).
- [ ] All files (not excluded) are copied to the destination directory.
## Templates
- [ ] Site configuration data is available in layouts and partials.
- [ ] Page data is available in page partials and layouts (including post/taxonomy pages).
- [ ] Post data is available to the post template (as well as post page templates).
## Events
- [ ] All events are invoke their registered handlers and pass in the correct arguments.
## Customization
- [ ] User plugins are auto-loaded
- [ ] User plugins are used instead of system plugins if they have the same filename
- [ ] All system config settings can be overridden by user config or cli options.
